name: Profile QA - changed files
on: push

jobs:
  validate-changed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get changed profiles and extensions
        id: get-resources
        run: |
          changed_only=1
          source util/qaAutomation/getresources.sh
          echo "::set-output name=zib_profiles::"$zib_profiles
          echo "::set-output name=other_profiles::"$other_profiles
          echo "::set-output name=conceptmaps::"$conceptmaps
          echo "::set-output name=examples::"$examples

      - name: Restore validator cache
        uses: actions/cache@v2
        with:
          path: ~/.fhir/packages
          key: fhir-cache

      - name: Create ig with the ProfileGuidelines resources
        run: bash util/qaAutomation/mkprofilingig.sh
      - name: Validate zib profiles
        uses: pieter-edelman-nictiz/hl7-fhir-validator-action@v0.13
        with:
          version: "4.0"
          ig: ig/
          recurse: true
          profile: http://nictiz.nl/fhir/StructureDefinition/ProfilingGuidelinesR4-StructureDefinitions-Zib
          source:  ${{ steps.get-resources.outputs.zib_profiles }}
          fail-at: warning
          ignored-issues: known-issues.yml
      - name: Validate other profiles
        uses: pieter-edelman-nictiz/hl7-fhir-validator-action@v0.13
        with:
          version: "4.0"
          ig: ig/
          recurse: true
          profile: http://nictiz.nl/fhir/StructureDefinition/ProfilingGuidelinesR4-StructureDefinitions
          source:  ${{ steps.get-resources.outputs.other_profiles }}
          fail-at: warning
          ignored-issues: known-issues.yml
      - name: Validate ConceptMaps
        uses: pieter-edelman-nictiz/hl7-fhir-validator-action@v0.13
        with:
          version: "4.0"
          ig: ig/
          recurse: true
          profile: http://nictiz.nl/fhir/StructureDefinition/ProfilingGuidelinesR4-ConceptMaps
          source:  ${{ steps.get-resources.outputs.conceptmaps }}
          fail-at: warning
          ignored-issues: known-issues.yml
      - name: Validate examples
        uses: pieter-edelman-nictiz/hl7-fhir-validator-action@v0.13
        with:
          version: "4.0"
          ig: resources/
          recurse: true
          source:  ${{ steps.get-resources.outputs.examples }}
          fail-at: warning
          ignored-issues: known-issues.yml

      - name: Install Firely Terminal
        run: dotnet tool install -g firely.terminal
      - name: Create snapshots in JSON format
        run: bash util/qaAutomation/generatezibsnapshots.sh ${{ steps.get-resources.outputs.zib_profiles }}
      - name: Check zib compliance
        uses: pieter-edelman-nictiz/zib-compliance-fhir@action
        with:
          max-file: qa/zibs2020.max
          structuredefinitions: snapshots/*
          zib-release: 2020
          fail-at: warning
          zib-deviations: known-issues.yml
