name: Profile QA - full repository
on: pull_request

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Restore validator cache
        uses: actions/cache@v2
        with:
          path: ~/.fhir/packages
          key: fhir-cache
      - name: Copy conformance profile to the ig
        run: cp qa/ProfilingGuidelinesR4.xml resources/
      - name: Validate profiles
        uses: pieter-edelman-nictiz/hl7-fhir-validator-action@v0.9
        with:
          version: "4.0"
          ig: resources/
          recurse: true
          source: resources/zib-*
      - name: Validate examples
        uses: pieter-edelman-nictiz/hl7-fhir-validator-action@v0.9
        with:
          version: "4.0"
          ig: resources/
          recurse: true
          source: example/*

      - name: Install Firely Terminal
        run: dotnet tool install -g firely.terminal
      - name: Create snapshots in JSON format
        run: |
          mkdir snapshots
          fhir install hl7.fhir.r4.core 4.0.1
          for sd in resources/zib-*; do
            base=$(basename $sd .xml);
            fhir push $sd
            fhir snapshot
            fhir save snapshots/$base.json --json
          done
      - name: Check zib compliance
        uses: pieter-edelman-nictiz/zib-compliance-fhir@action
        with:
          max-file: zibs2020.max
          structuredefinitions: snapshots/*
          zib-release: 2020
          allow-level: 2

